# A workflow to build the platform(s) in this repository using certain configurations.
#
##
# Copyright (c) Microsoft Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: "Platform CI"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # A job to produce the environment constants for this repository, so that the build job can
  # generate its matrix.
  vars:
    name: Get Repository Constants
    uses: ./.github/workflows/constants.yml
  
  build-windows:
    name: Windows ${{ matrix.platform }} ${{ matrix.architecture }} ${{ matrix.target }} ${{ matrix.tool-chain }}

    needs: vars

    strategy:
      fail-fast: false

      matrix:
        target: [DEBUG, RELEASE]
        tool-chain: [CLANGPDB, VS2022]
        platform: [Q35, SBSA]
        architecture: ['', 'IA32,X64']
        exclude:
          # Exclude SBSA IA32,X64 builds since they are not supported
          - platform: SBSA
            architecture: "IA32,X64"
          ##############################
          # Temporary Filters for Bugs #
          ##############################
          # Exclude CLANGPDB RELEASE builds due to PEI bug
          - tool-chain: CLANGPDB
            target: RELEASE
          # Exclude SBSA CLANG builds due to ldr assembly issue
          - tool-chain: CLANGPDB
            platform: SBSA
    
    uses: ./.github/workflows/run-platform.yml
    with:
      platform-config: ${{ matrix.platform == 'Q35' && 'Platforms/QemuQ35Pkg/PlatformBuild.py' || 'Platforms/QemuSbsaPkg/PlatformBuild.py' }}
      platform-name: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
      target: ${{ matrix.target }}
      tool-chain: ${{ matrix.tool-chain }}
      os: windows-latest
      python-version: ${{ needs.vars.outputs.python-version }}
      qemu-core-count: ${{ needs.vars.outputs.qemu-core-count }}
  
  ubuntu-latest:
    name: Ubuntu ${{ matrix.platform }} ${{ matrix.architecture }} ${{ matrix.target }} ${{ matrix.tool-chain }}

    needs: vars

    strategy:
      fail-fast: false

      matrix:
        target: [DEBUG, RELEASE]
        tool-chain: [CLANGPDB, GCC5]
        platform: [Q35, SBSA]
        architecture: ['', 'IA32,X64']
        exclude:
          # Exclude SBSA IA32,X64 builds since they are not supported
          - platform: SBSA
            architecture: "IA32,X64"
          ##############################
          # Temporary Filters for Bugs #
          ##############################
          # Exclude CLANGPDB RELEASE builds due to PEI bug
          - tool-chain: CLANGPDB
            target: RELEASE
          # Exclude SBSA CLANG builds due to ldr assembly issue
          - tool-chain: CLANGPDB
            platform: SBSA
    
    uses: ./.github/workflows/run-platform.yml
    with:
      platform-config: ${{ matrix.platform == 'Q35' && 'Platforms/QemuQ35Pkg/PlatformBuild.py' || 'Platforms/QemuSbsaPkg/PlatformBuild.py' }}
      platform-name: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
      target: ${{ matrix.target }}
      tool-chain: ${{ matrix.tool-chain }}
      os: ubuntu-latest
      container-image: ${{ needs.vars.outputs.container-image }}
      python-version: ${{ needs.vars.outputs.python-version }}
      qemu-core-count: ${{ needs.vars.outputs.qemu-core-count }}
