# A workflow to build the platform(s) in this repository using certain configurations.
#
# This workflow goes down two different paths based on whether HAF TFA needs to be built. This is
# because HAF TFA can only be built on linux, but the HAF TFA binaries are needed for the windows
# build. Due to this, if HAF TFA needs to be rebuilt, then the windows build needs to wait for the
# linux build to finish, so that it can consume it's artifacts.
#
# This, the first step is to check if HAF TFA needs to be re-built which is determined by the
# changed files in the pull request.
#
# If HAF TFA does not need to be built, then the `build-linux` and `build-windows` steps will build
# without the command line argument `HAF_TFA_BUILD=TRUE` and the `build-windows-haf-tfa` step will
# be skipped.
#
# If HAF TFA does need to be built, then the `build-linux` step will be built with the command line
# argument `HAF_TFA_BUILD=TRUE`, which will not only build HAF TFA, but will also output the HAF
# TFA artifacts as a build artifact. Then the `build-windows-haf-tfa` step will download the HAF
# TFA artifacts and use them for its own build.
#
##
# Copyright (c) Microsoft Corporation.
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: "Platform CI"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # A job to produce the environment constants for this repository, so that the build job can
  # generate its matrix.
  vars:
    name: Get Repository Constants
    uses: ./.github/workflows/constants.yml
  
  check-haf-tfa-build:
    name: Check if HAF TFA needs to be built
    runs-on: ubuntu-latest

    outputs:
      build-haf-tfa: ${{ steps.check.outputs.build-haf-tfa }}

    steps:
      - name: Check if HAF TFA needs to be build
        id: check
        shell: bash
        run: |
          # Check changed files for any that would require a HAF TFA build
          echo "build-haf-tfa=false" >> $GITHUB_OUTPUT

  
  build-linux:
    name: Ubuntu ${{ matrix.platform }} ${{ matrix.architecture }} ${{ matrix.target }} ${{ matrix.tool-chain }}

    needs: [vars, check-haf-tfa-build]

    strategy:
      fail-fast: false

      matrix:
        target: [DEBUG, RELEASE]
        tool-chain: [CLANGPDB, GCC5]
        platform: [Q35, SBSA]
        architecture: ['', 'IA32,X64']
        exclude:
          # Exclude SBSA IA32,X64 builds since they are not supported
          - platform: SBSA
            architecture: "IA32,X64"
          ##############################
          # Temporary Filters for Bugs #
          ##############################
          # Exclude CLANGPDB RELEASE builds due to PEI bug
          - tool-chain: CLANGPDB
            target: RELEASE
          # Exclude SBSA CLANG builds due to ldr assembly issue
          - tool-chain: CLANGPDB
            platform: SBSA
    
    uses: ./.github/workflows/run-platform.yml
    with:
      platform-config: ${{ matrix.platform == 'Q35' && 'Platforms/QemuQ35Pkg/PlatformBuild.py' || 'Platforms/QemuSbsaPkg/PlatformBuild.py' }}
      platform-name: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
      target: ${{ matrix.target }}
      tool-chain: ${{ matrix.tool-chain }}
      os: ubuntu-latest
      container-image: ${{ needs.vars.outputs.container-image }}
      python-version: ${{ needs.vars.outputs.python-version }}
      qemu-core-count: ${{ needs.vars.outputs.qemu-core-count }}
      extra-stuart-args: ${{ needs.check-haf-tfa-build.outputs.build-haf-tfa == 'true' && 'HAF_TFA_BUILD=TRUE' || '' }}

  # This windows build relies on the bundled HAF TFA extdep, so it is skipped if we need to build HAF TFA.
  build-windows:
    name: Windows ${{ matrix.platform }} ${{ matrix.architecture }} ${{ matrix.target }} ${{ matrix.tool-chain }}

    needs: [vars, check-haf-tfa-build]

    if: needs.check-haf-tfa-build.outputs.build-haf-tfa == 'false'

    strategy:
      fail-fast: false

      matrix:
        target: [DEBUG, RELEASE]
        tool-chain: [CLANGPDB, VS2022]
        platform: [Q35, SBSA]
        architecture: ['', 'IA32,X64']
        exclude:
          # Exclude SBSA IA32,X64 builds since they are not supported
          - platform: SBSA
            architecture: "IA32,X64"
          #########################################
          # Temporary Filters until only CLANGPDB #
          #########################################
          - platform: SBSA
            tool-chain: VS2022
          ##############################
          # Temporary Filters for Bugs #
          ##############################
          # Exclude CLANGPDB RELEASE builds due to PEI bug
          - tool-chain: CLANGPDB
            target: RELEASE
          # Exclude SBSA CLANG builds due to ldr assembly issue
          - tool-chain: CLANGPDB
            platform: SBSA
    
    uses: ./.github/workflows/run-platform.yml
    with:
      platform-config: ${{ matrix.platform == 'Q35' && 'Platforms/QemuQ35Pkg/PlatformBuild.py' || 'Platforms/QemuSbsaPkg/PlatformBuild.py' }}
      platform-name: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
      target: ${{ matrix.target }}
      tool-chain: ${{ matrix.tool-chain }}
      os: windows-latest
      python-version: ${{ needs.vars.outputs.python-version }}
      qemu-core-count: ${{ needs.vars.outputs.qemu-core-count }}

  # This windows build relies on the HAF TFA produced by the ubuntu build, but it only runs if we need to build HAF TFA.
  build-windows-haf-tfa:
    name: Windows ${{ matrix.platform }} ${{ matrix.architecture }} ${{ matrix.target }} ${{ matrix.tool-chain }}

    needs: [vars, check-haf-tfa-build, build-linux]

    if: needs.check-haf-tfa-build.outputs.build-haf-tfa == 'true'

    strategy:
      fail-fast: false

      matrix:
        target: [DEBUG, RELEASE]
        tool-chain: [CLANGPDB, VS2022]
        platform: [Q35, SBSA]
        architecture: ['', 'IA32,X64']
        exclude:
          # Exclude SBSA IA32,X64 builds since they are not supported
          - platform: SBSA
            architecture: "IA32,X64"
          #########################################
          # Temporary Filters until only CLANGPDB #
          #########################################
          - platform: SBSA
            tool-chain: VS2022
          ##############################
          # Temporary Filters for Bugs #
          ##############################
          # Exclude CLANGPDB RELEASE builds due to PEI bug
          - tool-chain: CLANGPDB
            target: RELEASE
          # Exclude SBSA CLANG builds due to ldr assembly issue
          - tool-chain: CLANGPDB
            platform: SBSA
    
    uses: ./.github/workflows/run-platform.yml
    with:
      platform-config: ${{ matrix.platform == 'Q35' && 'Platforms/QemuQ35Pkg/PlatformBuild.py' || 'Platforms/QemuSbsaPkg/PlatformBuild.py' }}
      platform-name: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
      target: ${{ matrix.target }}
      tool-chain: ${{ matrix.tool-chain }}
      os: windows-latest
      python-version: ${{ needs.vars.outputs.python-version }}
      qemu-core-count: ${{ needs.vars.outputs.qemu-core-count }}
